name: Update MikroTik CZ-SK Adlist

on:
  schedule:
    - cron: '0 3 * * *' # Každú noc o 03:00 UTC
  workflow_dispatch: # Možnosť spustiť manuálne

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Povolenie na zápis do repozitára

    steps:
    - name: Checkout repozitára
      uses: actions/checkout@v4

    - name: Spustenie konverzného skriptu
      run: python3 convert.py

    - name: Uloženie a push zmien
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add cz-sk-adlist.txt
        # Opravený zápis URL adresy pomocou systémovej premennej $GITHUB_REPOSITORY
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automatická aktualizácia adlistu" && git push "https://x-access-token:${GITHUB_TOKEN}@://github.com{GITHUB_REPOSITORY}.git" HEAD:main)
