name: Update MikroTik CZ-SK Adlist

on:
  schedule:
    - cron: '0 3 * * *' # Každú noc o 03:00 UTC
  workflow_dispatch: # Možnosť spustiť manuálne

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Povolenie na zápis do repozitára

    steps:
    - name: Checkout repozitára
      uses: actions/checkout@v4

    - name: Spustenie konverzného skriptu
      run: python3 convert.py

    - name: Uloženie a push zmien
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add cz-sk-adlist.txt
        # Ak nie sú zmeny, skript neskončí chybou. Ak sú, urobí sa čistý push do vetvy main.
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automatická aktualizácia adlistu" && git push origin HEAD:main)
