name: Update MikroTik CZ-SK Adlist

on:
  schedule:
    - cron: '0 3 * * *' # Spustí sa každú noc o 03:00 UTC
  workflow_dispatch: # Umožní spustiť aktualizáciu aj manuálne stlačením tlačidla

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dôležité: povolenie na zápis vyčisteného zoznamu späť do repozitára

    steps:
    - name: Checkout repozitára
      uses: actions/checkout@v4

    - name: Nastavenie Pythonu
      uses: actions/setup-python@v5
      with:
        python-python-version: '3.x'

    - name: Spustenie konverzného skriptu
      run: python convert.py

    - name: Uloženie a push zmien
      run: |
        git config --local user.email "github-actions[bot]@://github.com"
        git config --local user.name "github-actions[bot]"
        git add cz-sk-adlist.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automatická aktualizácia adlistu" && git push)
